TheSocialNetwork/urls.py
from django.contrib import admin
from django.urls import path, include

from social import views

urlpatterns = [
    path('', views.home, name='home'),
    path('social/', include('social.urls')),
    path('admin/', admin.site.urls),
]

social/urls.py
from django.urls import path

from . import views

app_name = 'social'
urlpatterns = [
    path('timeline/', views.timeline, name='timeline'),
    path('search/', views.search, name="search"),
    path("friends/", views.friends_view, name="friends"),
    path("chats/", views.chats_manager, name="create_or_get_chat"),
    path("post_chat_message/<int:friend_pk>/<int:chat_pk>/", views.post_chat_message, name="post_chat_message"),
    path("friend/<int:friend_pk>", views.friend_request, name="friend_request"),
    path("friend/<str:friend_usuario_first_name>/profile", views.friend_prof, name='friend_profile'),
    path("respond/<int:request_pk>/<int:accepted>", views.respond_request, name="respond_request"),
    path("unfriend/<int:friend_pk>/<str:view>", views.unfriend, name="unfriend"),
    path('asocia_usuario/', views.asocia_usuario, name='asocia_usuario'),
    path("register/", views.register, name="register"),
    path("login/", views.login_view, name="login_view"),
    path("logout/", views.logout_view, name="logout_view"),
    path("profile/", views.profile, name="profile"),
    path("profile/picture", views.profile_pic, name="profile_pic"),
    path("profile/delete-pic", views.delete_pic, name="delete_pic"),
    path('profile/delete', views.delete_prof, name="delete_prof")

]

social/models.py
from datetime import datetime

from django.conf import settings
from django.db import models

PENDING_STATUS = 1
ACCEPTED_STATUS = 2
REJECTED_STATUS = 3
IGNORED_STATUS = 4
CANCELED_STATUS = 5

REQUEST_STATUS_CHOICES = (
    (PENDING_STATUS, "Friend Request Pending"),
    (ACCEPTED_STATUS, "Friend Request Accepted"),
    (REJECTED_STATUS, "Friend Request  Rejected"),
    (IGNORED_STATUS, "Friend Request Ignored"),
    (CANCELED_STATUS, "Friend Request Canceled"),
)


class FriendRequested(models.Model):
    remitente = models.ForeignKey('SocialNetworkUser', related_name='fuente', on_delete=models.CASCADE)
    destinatario = models.ForeignKey('SocialNetworkUser', related_name='receptor', on_delete=models.CASCADE)
    status = models.IntegerField(choices=REQUEST_STATUS_CHOICES, default=PENDING_STATUS)


class SocialNetworkUser(models.Model):
    usuario = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    friends = models.ManyToManyField("self")
    requesting = models.ManyToManyField(FriendRequested)
    handle = models.CharField(max_length=10, default="")
    has_pic = models.BooleanField(default=False)

    def __str__(self):
        return self.usuario.username


class Chat(models.Model):
    creation_date = models.DateTimeField('date created')
    name = models.CharField(max_length=80)


class Message(models.Model):
    text = models.TextField()
    pub_date = models.DateTimeField('date published', default=datetime.now())
    author = models.ForeignKey(SocialNetworkUser, on_delete=models.CASCADE)
    recipients = models.ManyToManyField(SocialNetworkUser, through="Recibido", related_name="friend_list", blank=True)
    chat = models.ForeignKey(Chat, on_delete=models.SET_NULL, null=True)

    def __str__(self):
        return self.text


class UploadedPic(models.Model):
    pic = models.BinaryField(db_column='pic', blank=True, editable=True)
    tipo_mime = models.CharField(u"tipo MIME", max_length=255)
    user = models.CharField(max_length=255, default="")

    def __str__(self):
        return u"%s:%s" % (self.id, self.tipo_mime)


class Recibido(models.Model):
    message_id = models.ForeignKey(Message, on_delete=models.CASCADE)
    user_id = models.ForeignKey(SocialNetworkUser, on_delete=models.CASCADE)

social/forms.py
from django import forms
from django.core.exceptions import ValidationError

from social.widgets import BuscadorDeUsuarioField


class ShoutForm(forms.Form):
    text = forms.CharField(widget=forms.Textarea(attrs={'rows': 4, 'cols': 60}), label='Shout', max_length=240,
                           required=True)


class ChatForm(forms.Form):
    text = forms.CharField(widget=forms.Textarea(attrs={'rows': 4, 'cols': 60}), label='Message Text', max_length=240,
                           required=True)


class CreateChatForm(forms.Form):
    chat_name = forms.CharField(label='Chat Name', max_length=80, required=True)
    text = forms.CharField(widget=forms.Textarea(attrs={'rows': 4, 'cols': 60}), label='Message Text', max_length=240,
                           required=True)


class SearchForm(forms.Form):
    username = forms.CharField(label='Search', max_length=120, required=False)


class ReceiverForm(forms.Form):
    user = forms.CharField(label='Search', max_length=20, required=False)


class RegisterForm(forms.Form):
    template = "social/register.html"
    buscador_de_usuario = BuscadorDeUsuarioField(url="/social/asocia_usuario/",
                                                 timeout_milliseconds=8000,
                                                 label=u"Nombre de usuario", initial=u"Buscar...",
                                                 required=True)
    password = forms.CharField(label=u'Contraseña', widget=forms.PasswordInput, required=True, strip=True)

    def clean_password(self):
        password = self.data['password']
        if len(password) < 8 or len(password) > 30:
            raise ValidationError("Password must be 8-30 characters long.")
        else:
            self.cleaned_data['password'] = self.data['password']
        return password


class LoginForm(forms.Form):
    template = "social/login.html"
    username = forms.CharField(label=u"Nombre de usuario", strip=True)
    password = forms.CharField(label=u'Contraseña', widget=forms.PasswordInput, strip=True)

    def clean_password(self):
        password = self.data['password']
        if len(password) < 8 or len(password) > 30:
            raise ValidationError("Password must be 8-30 characters long.")
        else:
            self.cleaned_data['password'] = self.data['password']
        return password


class ProfileHandle(forms.Form):
    template = "social/profile.html"
    handle = forms.CharField(strip=True, max_length=10)


class ProfilePic(forms.Form):
    template = "social/profile.html"
    pic = forms.ImageField(label="")

social/views.py
import base64
import json

import django
from django.conf import settings
from django.contrib.auth import get_user_model, load_backend
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.contrib.postgres.search import TrigramSimilarity
from django.core.exceptions import ObjectDoesNotExist
from django.db.models import Q, Subquery
from django.http import HttpResponseRedirect, HttpResponse, Http404
from django.shortcuts import get_object_or_404
from django.shortcuts import render, reverse
from django.utils import timezone
from django.views.decorators.cache import never_cache
from django.views.decorators.http import require_http_methods

from social.forms import ProfileHandle, ProfilePic
from social.forms import RegisterForm, LoginForm, ChatForm, SearchForm, ShoutForm, ReceiverForm, CreateChatForm
from .models import PENDING_STATUS, ACCEPTED_STATUS, \
    REJECTED_STATUS, IGNORED_STATUS, CANCELED_STATUS, REQUEST_STATUS_CHOICES
from .models import Recibido
from .models import SocialNetworkUser, Message, FriendRequested, Chat
from .models import UploadedPic


@never_cache
@require_http_methods(["POST"])
def asocia_usuario(request):
    content_type = "application/json"
    response = HttpResponse(content_type=content_type)
    try:
        User = get_user_model()
        usuario_existente = User.objects.get(username__iexact=request.POST.get('username', ""))
        response.write(json.dumps({"resultado": "Este usuario ya existe en el sistema.",
                                   "nombre_completo": usuario_existente.get_full_name(),
                                   "nombre_usuario": usuario_existente.username,
                                   "email": usuario_existente.email, }))
    except ObjectDoesNotExist:
        response.write(json.dumps(load_backend(settings.AUTH_BACKEND).get_user_info(request.POST.get('username', ""))))
    return response


@login_required
def home(request):
    return HttpResponseRedirect(reverse("social:timeline"))


@login_required
def friends_view(request):
    form = CreateChatForm()
    friends = request.user.socialnetworkuser.friends.all().values_list('id', 'usuario__username', 'usuario__first_name')
    return render(request, 'social/my_friends.html', {'my_friends_list': friends, 'form': form, })


def logout_view(request):
    django.contrib.auth.logout(request)
    return HttpResponseRedirect(settings.LOGIN_URL)


def login_view(request):
    if request.method == "POST":
        form = LoginForm(request.POST)
        if form.is_valid():
            backend = load_backend(settings.AUTH_BACKEND)
            user = backend.authenticate(request, form.cleaned_data['username'], form.cleaned_data['password'],
                                        must_exist=True)
            if user:
                django.contrib.auth.login(request, user)
                return HttpResponseRedirect(reverse("social:timeline"), request)
                # Authenticated
            else:
                # Not authenticated
                return render(request, "social/login.html",
                              context={'form': LoginForm(), 'error_message': "Username or password is incorrect"})
    elif request.method == "GET":
        return render(request, "social/login.html", context={'form': LoginForm()})


def register(request):
    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            auth_only_backend = load_backend(settings.AUTH_BACKEND)
            authenticated = auth_only_backend.authenticate(request, form.cleaned_data['buscador_de_usuario'],
                                                           form.cleaned_data['password'], must_exist=False)
            if authenticated:
                if not SocialNetworkUser.objects.filter(usuario__username=authenticated.username).exists():
                    user_info = auth_only_backend.get_user_info(form.cleaned_data['buscador_de_usuario'])
                    user = auth_only_backend.create_user(authenticated, user_info)
                    django.contrib.auth.login(request, user)
                    return HttpResponseRedirect(reverse("social:timeline"))
                else:
                    return render(request, "social/register.html", context={'form': form,
                                                                            'error_message': 'User already exists'})
            else:
                return render(request, "social/register.html", context={'form': form,
                                                                        'error_message': 'Username or Password is incorrect.'})
        else:
            return render(request, "social/register.html", context={'form': form})
    elif request.method == 'GET':
        return render(request, "social/register.html", context={'form': RegisterForm()})
    else:
        return Http404()


@login_required
def unfriend(request, friend_pk, view):
    get_object_or_404(SocialNetworkUser, pk=request.user.socialnetworkuser.id).friends.remove(friend_pk)
    return HttpResponseRedirect(reverse('social:'+view))


@login_required
def search(request):
    users = SocialNetworkUser.objects.exclude(usuario=request.user)
    auth = request.user.socialnetworkuser

    if request.method == 'POST':
        form = SearchForm(request.POST)
        if form.is_valid():
            clean_search_name = form.cleaned_data["username"]
            if clean_search_name != '':
                users = users.annotate(
                    similarity=TrigramSimilarity('usuario__username', clean_search_name)).filter(
                    Q(usuario__username__icontains=clean_search_name) | Q(similarity__gt=0.5)).order_by('-similarity')
    else:
        form = SearchForm()
    context = {
        'users': [(user, user.friends.filter(id=auth.id).exists(), FriendRequested.objects.filter(destinatario=user, remitente=auth,
                                                                    status=PENDING_STATUS).first()) for user in users],
        'form': form,
        'chat': CreateChatForm(),
        'auth_user': auth
    }
    return render(request, 'social/search.html', context)


def friend_request(request, friend_pk):
    if not FriendRequested.objects.filter(remitente=request.user.socialnetworkuser, destinatario_id=friend_pk,
                                          status=PENDING_STATUS).first():
        req = FriendRequested.objects.create(remitente=request.user.socialnetworkuser, destinatario_id=friend_pk)
        request.user.socialnetworkuser.requesting.add(req)
    return HttpResponseRedirect(reverse('social:search'))


def respond_request(request, request_pk, accepted):
    req = get_object_or_404(FriendRequested, pk=request_pk)
    dest = req.destinatario
    rem = req.remitente
    status_choices = dict(REQUEST_STATUS_CHOICES)
    if accepted == ACCEPTED_STATUS:
        dest.friends.add(rem)
        req.status = ACCEPTED_STATUS
        message = Message.objects.create(text=status_choices.get(ACCEPTED_STATUS), author=dest,
                                         pub_date=timezone.now(), chat=Chat.objects.create(name='New Friends Chat', creation_date=timezone.now()))
        Recibido.objects.create(message_id=message, user_id=rem)
    elif accepted == REJECTED_STATUS:
        req.status = REJECTED_STATUS
        message = Message.objects.create(text=status_choices.get(REJECTED_STATUS), author=dest,
                                         pub_date=timezone.now(), chat=Chat.objects.create(name='Friend Request Rejected', creation_date=timezone.now()))
        Recibido.objects.create(message_id=message, user_id=rem)
    elif accepted == IGNORED_STATUS:
        req.status = IGNORED_STATUS
    elif accepted == CANCELED_STATUS:
        req.status = CANCELED_STATUS
        req.save()
        return HttpResponseRedirect(reverse('social:search'))
    req.save()
    return HttpResponseRedirect(reverse('social:timeline'))


def search_view_unfriend(request, friend_pk):
    get_object_or_404(SocialNetworkUser, pk=request.user.socialnetworkuser.id).friends.remove(friend_pk)
    return HttpResponseRedirect(reverse('social:search'))


@login_required
def timeline(request):
    displayedMessages = Recibido.objects.filter(Q(user_id=request.user.socialnetworkuser) | Q(message_id__author=
                                                request.user.socialnetworkuser)).order_by('-message_id__pub_date').\
                                                distinct('message_id__pub_date', 'message_id__author')
    senderform = SearchForm(request.POST)
    receiverform = ReceiverForm(request.POST)
    if request.method == 'POST':
        form = ShoutForm(request.POST or None)
        if form.is_valid():
            message = Message.objects.create(text=request.POST["text"], author=request.user.socialnetworkuser,
                                             pub_date=timezone.now())
            for recipient in request.user.socialnetworkuser.friends.all().iterator():
                Recibido.objects.create(message_id=message, user_id=recipient)
            return HttpResponseRedirect(reverse("social:timeline"))
        if request.POST['filter'] == '1':
            if senderform.is_valid():
                username = senderform.cleaned_data["username"]
                if request.POST["username"] != '':
                    displayedMessages = Recibido.objects.filter(message_id__author__usuario__username__icontains=
                                                                username).order_by('-message_id__pub_date').\
                                                                distinct('message_id__pub_date', 'message_id__author')
        if request.POST['filter'] == '2':
            if receiverform.is_valid():
                user = receiverform.cleaned_data["user"]
                if request.POST["user"] != '':

social/templates/social/base.html
{% load static %}

<html>
<header>
    <link rel="stylesheet" type="text/css" href="{% static 'social/profile.css' %}">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <!-- jQuery and other JS resources-->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
            integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
            crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
            integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
            crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
            integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
            crossorigin="anonymous">

    </script>

</header>
<body onload="//setTimeout(function(){location.reload();}, 10000);">

<!-- Navbar -->
<nav class="navbar navbar-expand-lg navbar-dark bg-info">
    <span class="navbar-brand mb-0 h1">Social</span>
    <div id="navbarNav">
        <ul class="navbar-nav">

            {% block active %}
                <li class="nav-item active">
                    <a class="nav-link" id="navTimeline" href="{%  url "social:timeline" %}">Timeline<span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" id="navSearch" href="{%  url "social:search" %}">Search</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" id="navMyFriends" href=" {%  url "social:friends" %}">My friends</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" id="navChats" href="{% url "social:create_or_get_chat" %}">Chats</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" id="navProfile" href="{% url "social:profile" %}">Profile</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" id="navLogout" href="{% url "social:logout_view" %}">Logout</a>
                </li>
            {% endblock%}

        </ul>
    </div>
</nav>

{% block content %}
{% endblock%}

</body>
</html>

social/templates/social/chat.html
{% extends 'social/base.html' %}

{% block active %}
    <li class="nav-item">
        <a class="nav-link" id="navTimeline" href="{%  url "social:timeline" %}">Timeline</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" id="navSearch" href="{%  url "social:search" %}">Search</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" id="navMyFriends" href=" {%  url "social:friends" %}">My friends</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" id="navChats" href="{% url "social:create_or_get_chat" %}">Chats</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" id="navProfile" href="{% url "social:profile" %}">Profile</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" id="navLogout" href="{% url "social:logout_view" %}">Logout</a>
    </li>
{% endblock%}

{% block content %}
    <h1><strong> {{ chat_name }} </strong></h1>
    <h2> Created: {{ date }}</h2>
    <br> <br>

    <form action="{% url "social:post_chat_message" friend_pk chat_id%}" method="post">
        {% csrf_token %}
        {{ chat_form }}
        <input class="btn btn-info btn-sm" id="submitButton" type="submit" value="Send">
    </form>

    <ul>
        {%  for text, author, recipient, pub_date in recibido_messages %}

            <li> <div class="card" style="width: 30rem;">
                <div class="card-body">

                    <h5 class="card-title">{{ author }} -> {{ recipient }}</h5>

                    <div><p>{{ text }}</p></div>
                    <div style="float:right" ><p> <strong> posted </strong> {{ pub_date }}</p></div>
                </div>
            </div>
            </li><br>

        {% endfor %}
    </ul>

{% endblock %}

social/templates/social/friend_profile.html
{% extends 'social/base.html' %}
{% load static %}


{% block active %}
    <li class="nav-item">
        <a class="nav-link" id="navTimeline" href="{%  url "social:timeline" %}">Timeline</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" id="navSearch" href="{%  url "social:search" %}">Search</a>
    </li>
    <li class="nav-item active">
        <a class="nav-link" id="navMyFriends" href=" {%  url "social:friends" %}">My friends<span class="sr-only">(current)</span></a>
    </li>
    <li class="nav-item">
        <a class="nav-link" id="navChats" href="{% url "social:create_or_get_chat" %}">Chats</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" id="navProfile" href="{% url "social:profile" %}">Profile</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" id="navLogout" href="{% url "social:logout_view" %}">Logout</a>
    </li>

{% endblock%}

{% block content %}
    <h2> {{ friend.usuario.first_name }}'s Profile</h2>
    <h5>{{ friend.usuario.first_name }} {{ friend.usuario.last_name }} ({{ friend.usuario.username }})</h5>
    <h6><font color="#a9a9a9">@{{ friend.handle }}</font></h6>
    <div class="left">
        <div class="container">
            <img src="{{ pic_url }}" class="avatar" alt="Profile" />
        </div>
    </div>
{% endblock %}

social/templates/social/my_friends.html
{% extends 'social/base.html' %}

{% block active %}
    <li class="nav-item">
        <a class="nav-link" id="navTimeline" href="{%  url "social:timeline" %}">Timeline</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" id="navSearch" href="{%  url "social:search" %}">Search</a>
    </li>
    <li class="nav-item active">
        <a class="nav-link" id="navMyFriends" href=" {%  url "social:friends" %}">My friends<span class="sr-only">(current)</span></a>
    </li>
    <li class="nav-item">
        <a class="nav-link" id="navChats" href="{% url "social:create_or_get_chat" %}">Chats</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" id="navProfile" href="{% url "social:profile" %}">Profile</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" id="navLogout" href="{% url "social:logout_view" %}">Logout</a>
    </li>
{% endblock%}

{% block content %}

    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'social/style.css' %}">

    <h1> My Friends </h1>
    {% if my_friends_list %}
        <ul>
            {% for friend_id, friend_username, friend_first_name in my_friends_list %}
                <li>
                    {{ friend_username }}

                    <!-- Button trigger modal -->
                    <button class="btn btn-success btn-sm" data-toggle="modal" data-target="#Modal{{ forloop.counter }}">
                        Chat
                    </button>

                    <!-- Modal -->
                    <div class="modal fade" id="Modal{{ forloop.counter }}" tabindex="-1" role="dialog" aria-labelledby="ModalScrollableTitle" aria-hidden="true">
                        <div class="modal-dialog" role="document">
                            <div class="modal-content">
                                <div class="modal-header">

                                    <h5 class="modal-title" id="ModalScrollableTitle"> Start Chat </h5>

                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                        <span aria-hidden="true">&times;</span>
                                    </button>

                                </div>

                                <form action="{% url "social:create_or_get_chat"%}?friend_pk={{ friend_id }}" method="POST">
                                    {% csrf_token %}

                                    <div class="modal-body">
                                        <div class="container">
                                            {{ form }}
                                        </div>
                                    </div>

                                    <div class="modal-footer">
                                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                                        <input type="submit" class="btn btn-primary" value="Send">
                                    </div>
                                </form>

                            </div>
                        </div>
                    </div>

                    <a href="{% url "social:unfriend" friend_id "friends"%}" class="btn  btn-danger btn-sm" > Unfriend </a>
                    <a href="{% url "social:friend_profile" friend_first_name %}" class="btn btn-primary btn-sm" > Profile </a>
                    <br>
                    <br>

                </li>
            {% endfor %}
        </ul>
    {% else %}
        <p> You don't have friends. :( </p>
    {% endif %}
{% endblock %}

social/templates/social/profile.html
{% extends 'social/base.html' %}
{% load static %}

{% block active %}
    <li class="nav-item">
        <a class="nav-link" id="navTimeline" href="{%  url "social:timeline" %}">Timeline</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" id="navSearch" href="{%  url "social:search" %}">Search</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" id="navMyFriends" href=" {%  url "social:friends" %}">My friends</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" id="navChats" href="{% url "social:create_or_get_chat" %}">Chats</a>
    </li>
    <li class="nav-item active">
        <a class="nav-link" id="navProfile" href="{% url "social:profile" %}">Profile<span class="sr-only">(current)</span></a>
    </li>
    <li class="nav-item">
        <a class="nav-link" id="navLogout" href="{% url "social:logout_view" %}">Logout</a>
    </li>
{% endblock%}

{% block content %}

    <h2>Your Profile</h2>
    <h5>{{ request.user.first_name }} {{ request.user.last_name }}</h5>
    <h6><font color="#a9a9a9">@{{ request.user.socialnetworkuser.handle }}</font></h6>
    <div class="left">
        <div class="container">
            <img src="{{ pic_url }}" class="avatar" alt="Profile" />
        </div>
    </div>
    <form action="" method="POST">
        {% csrf_token %}
        {{ handle_form }}
        <button type="submit" class="btn btn-info btn-sm">Set handle</button>
    </form>
    {% if error_message %} <p> <strong> {{ error_message }}</strong> </p>{% endif %}
    <div class="left">
        <form enctype="multipart/form-data" action="{% url "social:profile_pic" %}" method="POST">
            {% csrf_token %}
            {{ pic_form }}
            <div>
                <button type="submit" class="btn btn-info btn-sm">Set profile picture</button>
            </div>
        </form>
        <form action="{% url "social:delete_pic" %}" method="POST">
            {% csrf_token %}
            <button type="submit" class="btn btn-danger btn-sm">Delete profile picture</button>
        </form>
        <form action="{% url "social:delete_prof" %}" method="POST">
            {% csrf_token %}
            <button type="submit" class="btn  btn-danger btn-sm">Delete account</button>
        </form>
    </div>
{% endblock %}

social/templates/social/search.html
{% extends 'social/base.html' %}

{% block active %}
    <li class="nav-item">
        <a class="nav-link" id="navTimeline" href="{%  url "social:timeline" %}">Timeline</a>
    </li>
    <li class="nav-item active">
        <a class="nav-link" id="navSearch" href="{%  url "social:search" %}">Search<span class="sr-only">(current)</span></a>
    </li>
    <li class="nav-item">
        <a class="nav-link" id="navMyFriends" href=" {%  url "social:friends" %}">My friends</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" id="navChats" href="{% url "social:create_or_get_chat" %}">Chats</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" id="navProfile" href="{% url "social:profile" %}">Profile</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" id="navLogout" href="{% url "social:logout_view" %}">Logout</a>
    </li>
{% endblock%}

{% block content %}

    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'social/style.css' %}">

    <h1>Search Users</h1>
    <form action="" method="POST">
        {% csrf_token %}
        {{ form }}
        <button class="btn btn-info btn-sm" name="search" type="submit">search</button>
    </form>
    <ul>
        {% for user, is_friend, f_request in users %}
            <li>
                {{ user.usuario.username }}
                {% if is_friend %}

                    <!-- Button trigger modal -->
                    <button class="btn btn-success btn-sm" data-toggle="modal" data-target="#Modal{{ forloop.counter }}">
                        Chat
                    </button>

                    <!-- Modal -->
                    <div class="modal fade" id="Modal{{ forloop.counter }}" tabindex="-1" role="dialog" aria-labelledby="ModalScrollableTitle" aria-hidden="true">
                        <div class="modal-dialog" role="document">
                            <div class="modal-content">
                                <div class="modal-header">

                                    <h5 class="modal-title" id="ModalScrollableTitle"> Start Chat </h5>

                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                        <span aria-hidden="true">&times;</span>
                                    </button>

                                </div>

                                <form action="{% url "social:create_or_get_chat"%}?friend_pk={{ user.id }}" method="POST">
                                    {% csrf_token %}
                                    <div class="modal-body">
                                        <div class="container">
                                            {{ chat }}
                                        </div>
                                    </div>

                                    <div class="modal-footer">
                                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                                        <input type="submit" class="btn btn-primary" value="Send">
                                    </div>
                                </form>

                            </div>
                        </div>
                    </div>
                    <a href="{% url "social:unfriend" user.id "search"%}" class="btn btn-danger btn-sm">Unfriend</a>
                {% elif f_request %}
                    <a href="{% url "social:respond_request" f_request.pk 5 %}" class="btn btn-danger btn-sm">Cancel Request</a>
                {% else %}
                    <a href="{% url "social:friend_request" user.id %}" class="btn btn-success btn-sm">Add Friend</a>
                {% endif %}

            </li><br>
        {% endfor %}
    </ul>
{% endblock%}